version: '3'
services:
  rabbit_server:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile.rabbit
    container_name: rabbitMQ
    ports:
      - 7000:7000
      - 17000:17000
    volumes:
      - .:/usr/src/app
    networks:
      - rabbitnet

  server:
    build: ./server
    volumes:
      - ./server:/app/
    stdin_open: true
    tty: true
    container_name: server
    ports:
      - 12000:12000
    networks:
      - rabbitnet
    restart: on-failure
    depends_on:
      - rabbit_server

  client:
    build: ./client
    stdin_open: true
    tty: true
    container_name: client
    volumes:
      - ./client:/app/
    networks:
      - rabbitnet
    restart: on-failure
    depends_on:
      - server

  client_2:
    build: ./client
    stdin_open: true
    tty: true
    container_name: client_2
    volumes:
      - ./client:/app/
    networks:
      - rabbitnet
    restart: on-failure
    depends_on:
      - server

networks:
  rabbitnet:
    driver: bridge
