# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msn.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msn.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tmsn.proto\"\x1b\n\x07Usuario\x12\x10\n\x08username\x18\x01 \x01(\t\"]\n\x07Mensaje\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x65misor\x18\x02 \x01(\t\x12\x10\n\x08receptor\x18\x03 \x01(\t\x12\x0f\n\x07mensaje\x18\x04 \x01(\t\x12\x13\n\x0bmarcatiempo\x18\x05 \x01(\t\"\x12\n\x03\x41\x63k\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t2\xeb\x01\n\x0bServidorMSN\x12&\n\x0eRecibirMensaje\x12\x08.Usuario\x1a\x08.Mensaje0\x01\x12\x1f\n\rEnviarMensaje\x12\x08.Mensaje\x1a\x04.Ack\x12&\n\x10\x44\x65volverUsuarios\x12\x08.Usuario\x1a\x08.Usuario\x12 \n\x0eValidarUsuario\x12\x08.Usuario\x1a\x04.Ack\x12(\n\x10\x44\x65volverMensajes\x12\x08.Usuario\x1a\x08.Mensaje0\x01\x12\x1f\n\rDesconectarse\x12\x08.Usuario\x1a\x04.Ackb\x06proto3')
)




_USUARIO = _descriptor.Descriptor(
  name='Usuario',
  full_name='Usuario',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='Usuario.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=40,
)


_MENSAJE = _descriptor.Descriptor(
  name='Mensaje',
  full_name='Mensaje',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Mensaje.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='emisor', full_name='Mensaje.emisor', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receptor', full_name='Mensaje.receptor', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mensaje', full_name='Mensaje.mensaje', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='marcatiempo', full_name='Mensaje.marcatiempo', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=135,
)


_ACK = _descriptor.Descriptor(
  name='Ack',
  full_name='Ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ack', full_name='Ack.ack', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=155,
)

DESCRIPTOR.message_types_by_name['Usuario'] = _USUARIO
DESCRIPTOR.message_types_by_name['Mensaje'] = _MENSAJE
DESCRIPTOR.message_types_by_name['Ack'] = _ACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Usuario = _reflection.GeneratedProtocolMessageType('Usuario', (_message.Message,), {
  'DESCRIPTOR' : _USUARIO,
  '__module__' : 'msn_pb2'
  # @@protoc_insertion_point(class_scope:Usuario)
  })
_sym_db.RegisterMessage(Usuario)

Mensaje = _reflection.GeneratedProtocolMessageType('Mensaje', (_message.Message,), {
  'DESCRIPTOR' : _MENSAJE,
  '__module__' : 'msn_pb2'
  # @@protoc_insertion_point(class_scope:Mensaje)
  })
_sym_db.RegisterMessage(Mensaje)

Ack = _reflection.GeneratedProtocolMessageType('Ack', (_message.Message,), {
  'DESCRIPTOR' : _ACK,
  '__module__' : 'msn_pb2'
  # @@protoc_insertion_point(class_scope:Ack)
  })
_sym_db.RegisterMessage(Ack)



_SERVIDORMSN = _descriptor.ServiceDescriptor(
  name='ServidorMSN',
  full_name='ServidorMSN',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=158,
  serialized_end=393,
  methods=[
  _descriptor.MethodDescriptor(
    name='RecibirMensaje',
    full_name='ServidorMSN.RecibirMensaje',
    index=0,
    containing_service=None,
    input_type=_USUARIO,
    output_type=_MENSAJE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='EnviarMensaje',
    full_name='ServidorMSN.EnviarMensaje',
    index=1,
    containing_service=None,
    input_type=_MENSAJE,
    output_type=_ACK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DevolverUsuarios',
    full_name='ServidorMSN.DevolverUsuarios',
    index=2,
    containing_service=None,
    input_type=_USUARIO,
    output_type=_USUARIO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ValidarUsuario',
    full_name='ServidorMSN.ValidarUsuario',
    index=3,
    containing_service=None,
    input_type=_USUARIO,
    output_type=_ACK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DevolverMensajes',
    full_name='ServidorMSN.DevolverMensajes',
    index=4,
    containing_service=None,
    input_type=_USUARIO,
    output_type=_MENSAJE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Desconectarse',
    full_name='ServidorMSN.Desconectarse',
    index=5,
    containing_service=None,
    input_type=_USUARIO,
    output_type=_ACK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVIDORMSN)

DESCRIPTOR.services_by_name['ServidorMSN'] = _SERVIDORMSN

# @@protoc_insertion_point(module_scope)
